export const SkillInitialData = [
    { name: "Acrobatics", attribute: "strength", proficiency: "untrained", item: 0, armor: 0 },
    { name: "Arcana", attribute: "intelligence", proficiency: "untrained", item: 0, armor: 0 },
    { name: "Athletics", attribute: "strength", proficiency: "untrained", item: 0, armor: 0 },
    { name: "Crafting", attribute: "intelligence", proficiency: "untrained", item: 0, armor: 0 },
    { name: "Deception", attribute: "charisma", proficiency: "untrained", item: 0, armor: 0 },
    { name: "Diplomacy", attribute: "charisma", proficiency: "untrained", item: 0, armor: 0 },
    { name: "Intimidation", attribute: "charisma", proficiency: "untrained", item: 0, armor: 0 },
    { name: "Lore", attribute: "intelligence", proficiency: "untrained", item: 0, armor: 0 },
    { name: "Medicine", attribute: "wisdom", proficiency: "untrained", item: 0, armor: 0 },
    { name: "Nature", attribute: "wisdom", proficiency: "untrained", item: 0, armor: 0 },
    { name: "Occultism", attribute: "intelligence", proficiency: "untrained", item: 0, armor: 0 },
    { name: "Performance", attribute: "charisma", proficiency: "untrained", item: 0, armor: 0 },
    { name: "Religion", attribute: "wisdom", proficiency: "untrained", item: 0, armor: 0 },
    { name: "Society", attribute: "intelligence", proficiency: "untrained", item: 0, armor: 0 },
    { name: "Stealth", attribute: "dexterity", proficiency: "untrained", item: 0, armor: 0 },
    { name: "Survival", attribute: "wisdom", proficiency: "untrained", item: 0, armor: 0 },
    { name: "Thievery", attribute: "dexterity", proficiency: "untrained", item: 0, armor: 0 },
];